
package views;

import abstractClasses.ICloseable;
import models.Towar;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

public class MagazynView extends javax.swing.JFrame  {
// implements ICloseable
    
    /**
     * Creates new form MagazynView
     */
    public MagazynView() {
        towary = new ArrayList<>();
        towary.add(new Towar("Towar 1", 10.99));
        towary.add(new Towar("Towar 2", 9.99));
        towary.add(new Towar("Towar 3", 8.99));
        
        initComponents();
        
        iloscElementowLabel.setText(String.valueOf(towary.size()));
        numerWybranegoElementuLabel.setText(String.valueOf("1"));
        wybranyTowar = towary.get(0);
        aktualizujDaneWybranegoTowaru();
        setVisible(true);
    }
    
    private void aktualizujDaneWybranegoTowaru(){
        if(wybranyTowar ==  null){
            JOptionPane.showConfirmDialog(rootPane, "Nie wybrano towaru.");
            return;
        } 
        nazwaTowaruTextField.setText(wybranyTowar.getNazwa());
        cenaTextField.setText(String.valueOf(wybranyTowar.getCena()));
        numerWybranegoElementuLabel.setText(String.valueOf(towary.size()));
    }
    
    private Object dodajTowar(Towar towar){
        towary.add(towar);
        wybranyTowar = towary.get(towary.size() - 1);
        aktualizujDaneWybranegoTowaru();
        iloscElementowLabel.setText(String.valueOf(towary.size()));
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PoprzedniButton = new javax.swing.JButton();
        DodajButton = new javax.swing.JButton();
        NastepnyButton = new javax.swing.JButton();
        UsunButton = new javax.swing.JButton();
        ZamknijButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nazwaTowaruLabel = new javax.swing.JLabel();
        cenaTowaruLabel = new javax.swing.JLabel();
        nazwaTowaruTextField = new javax.swing.JTextField();
        cenaTextField = new javax.swing.JTextField();
        numerWybranegoElementuLabel = new javax.swing.JLabel();
        iloscElementowLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PoprzedniButton.setText("Poprzedni");
        PoprzedniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoprzedniButtonActionPerformed(evt);
            }
        });

        DodajButton.setText("Dodaj");
        DodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajButtonActionPerformed(evt);
            }
        });

        NastepnyButton.setText("Następny");
        NastepnyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NastepnyButtonActionPerformed(evt);
            }
        });

        UsunButton.setText("Usuń");
        UsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunButtonActionPerformed(evt);
            }
        });

        ZamknijButton.setText("Zamknij");
        ZamknijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Magazyn");

        nazwaTowaruLabel.setText("Nazwa towaru");

        cenaTowaruLabel.setText("Cena");

        nazwaTowaruTextField.setText("próbny");

        cenaTextField.setText("1.0");

        numerWybranegoElementuLabel.setText("1");

        iloscElementowLabel.setText("2");

        jLabel4.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DodajButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PoprzedniButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NastepnyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(UsunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(152, 152, 152)
                                .addComponent(numerWybranegoElementuLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nazwaTowaruLabel)
                                    .addComponent(cenaTowaruLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nazwaTowaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ZamknijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iloscElementowLabel)
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numerWybranegoElementuLabel)
                    .addComponent(iloscElementowLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaTowaruLabel)
                    .addComponent(nazwaTowaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cenaTowaruLabel)
                    .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DodajButton)
                    .addComponent(UsunButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoprzedniButton)
                    .addComponent(NastepnyButton)
                    .addComponent(ZamknijButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZamknijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ZamknijButtonActionPerformed

    private void DodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajButtonActionPerformed
        JDialog dialog = new JDialog(this, "Nowy towar", true);
        // dialog.setContentPane(new Towar)
        dialog.setContentPane(new NowyTowarView(t -> { dialog.dispose(); return null; }, t -> dodajTowar(t)));
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_DodajButtonActionPerformed

    private void NastepnyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NastepnyButtonActionPerformed
        int index;
        if (wybranyTowar == null){
            index = 0;
        } else {
            index = towary.indexOf(wybranyTowar) + 1; 
            if (index >= towary.size()){
                index = 0;
            }
        }
        wybranyTowar = towary.get(index);
        aktualizujDaneWybranegoTowaru();
    }//GEN-LAST:event_NastepnyButtonActionPerformed

    private void UsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunButtonActionPerformed

        if(wybranyTowar ==  null){
            JOptionPane.showConfirmDialog(this, "Nie wybrano towaru.");
            return;
        } 
        towary.remove(wybranyTowar);
        try{
            PoprzedniButtonActionPerformed(evt);
        }
        catch (IndexOutOfBoundsException ex){
            
        }

    }//GEN-LAST:event_UsunButtonActionPerformed

    private void PoprzedniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoprzedniButtonActionPerformed
        int index;
        if (wybranyTowar == null){
            index = 0;
        } else {
            index = towary.indexOf(wybranyTowar) - 1; 
            if (index < 0){
                index = towary.size()-1;
            }
        }
        wybranyTowar = towary.get(index);
        aktualizujDaneWybranegoTowaru();
    }//GEN-LAST:event_PoprzedniButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagazynView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagazynView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagazynView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagazynView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagazynView().setVisible(true);
            }
        });
    }
    
//    @Override
//    public void Close(){
//        dispose();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajButton;
    private javax.swing.JButton NastepnyButton;
    private javax.swing.JButton PoprzedniButton;
    private javax.swing.JButton UsunButton;
    private javax.swing.JButton ZamknijButton;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JLabel cenaTowaruLabel;
    private javax.swing.JLabel iloscElementowLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nazwaTowaruLabel;
    private javax.swing.JTextField nazwaTowaruTextField;
    private javax.swing.JLabel numerWybranegoElementuLabel;
    // End of variables declaration//GEN-END:variables
    
    private List<Towar> towary; 
    private Towar wybranyTowar;
}
