/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.function.Function;
import models.Towar;
// import abstractClasses.ICloseable;


public class NowyTowarView extends javax.swing.JPanel {
    private final Function<Object, Object> functionZamknijModal;
    private final Function<Towar, Object> functionDodajTowar;
    
    public NowyTowarView(Function<Object, Object> functionZamknijModal, Function<Towar, Object> functionDodajTowar) {
        this.functionZamknijModal = functionZamknijModal;
        this.functionDodajTowar = functionDodajTowar;
        initComponents();
    }
 
//    private ICloseable closeableWindow;
//    
//    public ICloseable getCloseableWindow(){
//        return closeableWindow;
//    }
    
//    public NowyTowarView(/** ICloseable closeable **/) {
//        initComponents();
//        //closeableWindow = closeable;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        zapiszButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nazwaTowaruTextField = new javax.swing.JTextField();
        cenaTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Magazyn");

        zapiszButton.setText("Zapisz");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj");
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nazwa");

        jLabel3.setText("Cena");

        nazwaTowaruTextField.setText("jTextField1");
        nazwaTowaruTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazwaTowaruTextFieldActionPerformed(evt);
            }
        });

        cenaTextField.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zapiszButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anulujButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazwaTowaruTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(cenaTextField))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nazwaTowaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zapiszButton)
                    .addComponent(anulujButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        try{
            Towar towar = new Towar(nazwaTowaruTextField.getText(), Double.parseDouble(cenaTextField.getText()));
            functionDodajTowar.apply(towar);
            functionZamknijModal.apply(null);
        } catch(Exception e){
            //Obsługa wyjątku
        }
    }//GEN-LAST:event_zapiszButtonActionPerformed

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        //closeableWindow.Close();
        functionZamknijModal.apply(null);
    }//GEN-LAST:event_anulujButtonActionPerformed

    private void nazwaTowaruTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazwaTowaruTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazwaTowaruTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujButton;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nazwaTowaruTextField;
    private javax.swing.JButton zapiszButton;
    // End of variables declaration//GEN-END:variables
}
